// This file will be auto-generated by `supabase gen types typescript`
// For now, define a minimal type to satisfy imports

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string
          avatar_url?: string | null
        }
        Update: {
          display_name?: string
          avatar_url?: string | null
        }
      }
      games: {
        Row: {
          id: string
          name: string
          gm_id: string
          invite_code: string
          status: 'active' | 'archived'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          gm_id: string
          invite_code?: string
          status?: 'active' | 'archived'
        }
        Update: {
          name?: string
          status?: 'active' | 'archived'
        }
      }
      game_members: {
        Row: {
          id: string
          game_id: string
          user_id: string
          role: 'gm' | 'player'
          joined_at: string
        }
        Insert: {
          id?: string
          game_id: string
          user_id: string
          role?: 'gm' | 'player'
        }
        Update: {
          role?: 'gm' | 'player'
        }
      }
      characters: {
        Row: {
          id: string
          game_id: string
          user_id: string
          name: string
          career: string
          level: number
          experience: number
          gender: string
          age: number | null
          background_notes: string
          attributes: CharacterAttributes
          skills: Record<string, number>
          edge_current: number
          health_current: number | null
          talents: unknown[]
          cyberware: unknown[]
          inventory: unknown[]
          credits: number
          notes: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          game_id: string
          user_id: string
          name?: string
          career?: string
          level?: number
          experience?: number
          gender?: string
          age?: number | null
          background_notes?: string
          attributes?: CharacterAttributes
          skills?: Record<string, number>
          edge_current?: number
          health_current?: number | null
          talents?: unknown[]
          cyberware?: unknown[]
          inventory?: unknown[]
          credits?: number
          notes?: string
        }
        Update: {
          name?: string
          career?: string
          level?: number
          experience?: number
          gender?: string
          age?: number | null
          background_notes?: string
          attributes?: CharacterAttributes
          skills?: Record<string, number>
          edge_current?: number
          health_current?: number | null
          talents?: unknown[]
          cyberware?: unknown[]
          inventory?: unknown[]
          credits?: number
          notes?: string
        }
      }
      dice_rolls: {
        Row: {
          id: string
          game_id: string
          user_id: string
          character_id: string | null
          skill_name: string | null
          roll_data: unknown
          is_hidden: boolean
          created_at: string
        }
        Insert: {
          id?: string
          game_id: string
          user_id: string
          character_id?: string | null
          skill_name?: string | null
          roll_data: unknown
          is_hidden?: boolean
        }
        Update: never
      }
      shared_notes: {
        Row: {
          id: string
          game_id: string
          title: string
          content: string
          updated_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          game_id: string
          title?: string
          content?: string
          updated_by?: string | null
        }
        Update: {
          title?: string
          content?: string
          updated_by?: string | null
        }
      }
    }
  }
}

export type CharacterAttributes = {
  con: number
  str: number
  agi: number
  int: number
  edu: number
  per: number
  coo: number
}
