// Generated by `supabase gen types typescript --local`.
// Re-run that command after migrations and update the Character override below
// if a JSON column's runtime shape changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '12'
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      characters: {
        Row: {
          age: number | null
          assets: number
          attributes: Json
          background_notes: string
          career: string
          created_at: string
          credits: number
          cyberware: Json
          edge_current: number
          experience: number
          game_id: string
          gender: string
          health_current: number | null
          id: string
          inventory: Json
          level: number
          malfunction_allocations: Json
          name: string
          notes: string
          skills: Json
          talents: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          age?: number | null
          assets?: number
          attributes?: Json
          background_notes?: string
          career?: string
          created_at?: string
          credits?: number
          cyberware?: Json
          edge_current?: number
          experience?: number
          game_id: string
          gender?: string
          health_current?: number | null
          id?: string
          inventory?: Json
          level?: number
          malfunction_allocations?: Json
          name?: string
          notes?: string
          skills?: Json
          talents?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          age?: number | null
          assets?: number
          attributes?: Json
          background_notes?: string
          career?: string
          created_at?: string
          credits?: number
          cyberware?: Json
          edge_current?: number
          experience?: number
          game_id?: string
          gender?: string
          health_current?: number | null
          id?: string
          inventory?: Json
          level?: number
          malfunction_allocations?: Json
          name?: string
          notes?: string
          skills?: Json
          talents?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'characters_game_id_fkey'
            columns: ['game_id']
            isOneToOne: false
            referencedRelation: 'games'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'characters_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      dice_rolls: {
        Row: {
          character_id: string | null
          created_at: string
          game_id: string
          id: string
          is_hidden: boolean
          roll_data: Json
          skill_name: string | null
          user_id: string
        }
        Insert: {
          character_id?: string | null
          created_at?: string
          game_id: string
          id?: string
          is_hidden?: boolean
          roll_data: Json
          skill_name?: string | null
          user_id: string
        }
        Update: {
          character_id?: string | null
          created_at?: string
          game_id?: string
          id?: string
          is_hidden?: boolean
          roll_data?: Json
          skill_name?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'dice_rolls_character_id_fkey'
            columns: ['character_id']
            isOneToOne: false
            referencedRelation: 'characters'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'dice_rolls_game_id_fkey'
            columns: ['game_id']
            isOneToOne: false
            referencedRelation: 'games'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'dice_rolls_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      game_members: {
        Row: {
          game_id: string
          id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          game_id: string
          id?: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          game_id?: string
          id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'game_members_game_id_fkey'
            columns: ['game_id']
            isOneToOne: false
            referencedRelation: 'games'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'game_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      game_state: {
        Row: {
          assets: number
          combat: Json | null
          credits: number
          game_id: string
          inventory: Json
          updated_at: string
        }
        Insert: {
          assets?: number
          combat?: Json | null
          credits?: number
          game_id: string
          inventory?: Json
          updated_at?: string
        }
        Update: {
          assets?: number
          combat?: Json | null
          credits?: number
          game_id?: string
          inventory?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'game_state_game_id_fkey'
            columns: ['game_id']
            isOneToOne: true
            referencedRelation: 'games'
            referencedColumns: ['id']
          },
        ]
      }
      games: {
        Row: {
          created_at: string
          gm_id: string
          id: string
          invite_code: string
          name: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          gm_id: string
          id?: string
          invite_code?: string
          name: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          gm_id?: string
          id?: string
          invite_code?: string
          name?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'games_gm_id_fkey'
            columns: ['gm_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string
          id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      shared_notes: {
        Row: {
          content: string
          created_at: string
          game_id: string
          id: string
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content?: string
          created_at?: string
          game_id: string
          id?: string
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: string
          created_at?: string
          game_id?: string
          id?: string
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'shared_notes_game_id_fkey'
            columns: ['game_id']
            isOneToOne: false
            referencedRelation: 'games'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'shared_notes_updated_by_fkey'
            columns: ['updated_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      find_game_by_invite_code: {
        Args: { p_invite_code: string }
        Returns: {
          created_at: string
          gm_id: string
          id: string
          invite_code: string
          name: string
          status: string
          updated_at: string
        }
        SetofOptions: {
          from: '*'
          to: 'games'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      get_user_game_ids: { Args: { p_user_id: string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// ============================================================
// Application-level types: narrow JSON columns to runtime shapes.
// ============================================================

export type CharacterAttributes = {
  con: number
  str: number
  agi: number
  int: number
  edu: number
  per: number
  coo: number
}

export type TalentEntry = {
  name: string
  career: string
  tier: number
  acquiredAt: number
  granted?: boolean
}

export type CyberwareEntry = {
  name: string
  category: string
  tier: string
  installedAt: number
}

/**
 * An entry in a character's or a game's shared inventory.
 * - `catalog` items resolve stats by looking up `name` in `items.json`.
 * - `custom` items are free-text and carry their own description.
 * - `weapon` items reference `weapons.json` via `weaponRef`; `name` is the
 *   player-editable display (defaults to the rulebook's illustrative name).
 * - `armor` items reference `armors.json` via `armorRef`; same name pattern,
 *   plus a `currentDurability` per-instance state that depletes during play.
 * Future equipment types (drones) follow the same pattern.
 */
export type InventoryItem = {
  id: string
  source: 'catalog' | 'custom' | 'weapon' | 'armor'
  name: string
  description?: string
  quantity: number
  /** Free-form grouping ("backpack", "on ship") — players define their own. */
  location?: string
  /** Catalog reference for source='weapon'. */
  weaponRef?: string
  /** Catalog reference for source='armor'. */
  armorRef?: string
  /** Per-instance weapon magazine ammo (0..weapon.magazine). */
  currentAmmo?: number
  /** Per-instance armor durability that depletes during play (0..armor.durability). */
  currentDurability?: number
  /** Only meaningful for source='weapon' or 'armor' on a character (stripped on transfer to party). */
  equipped?: boolean
  /** Manufacturer name (catalog key into manufacturers.json) for source='weapon' or 'armor'. */
  manufacturerRef?: string
  /** Attached mod names. For armor: keys into armor-mods.json, gated by the armor's moddingOptions
   * and the effective mod limit. Weapon mods follow in phase B. */
  mods?: string[]
}

type CharacterRow = Database['public']['Tables']['characters']['Row']

export type Character = Omit<
  CharacterRow,
  | 'attributes'
  | 'skills'
  | 'talents'
  | 'cyberware'
  | 'inventory'
  | 'malfunction_allocations'
> & {
  attributes: CharacterAttributes
  skills: Record<string, number>
  talents: TalentEntry[]
  cyberware: CyberwareEntry[]
  inventory: InventoryItem[]
  /** Cyber Malfunction Table slot numbers (2-40) the player has allocated to.
   * Length equals current excess Cyberimmunity. Each slot can be allocated at
   * most once (rulebook example). */
  malfunction_allocations: number[]
}

/**
 * One participant in the current combat encounter. AP can go negative when
 * an action overspends — the excess subtracts from the next round (§200).
 */
export type CombatParticipant = {
  characterId: string
  /** Snapshot at round-start so renaming a character mid-round doesn't shuffle the bar. */
  name: string
  /** Coolness at round-start — used for tiebreaks (§202). */
  coolness: number
  /** Derived `actionPoints` at round-start. */
  baseAp: number
  /** 1d6 initiative roll for this round. */
  rolled: number
  /** Remaining AP this round. May go negative. */
  ap: number
}

export type CombatState = {
  round: number
  /** ISO timestamp of when this combat started (for audit/log purposes). */
  startedAt: string
  participants: CombatParticipant[]
}

type GameStateRow = Database['public']['Tables']['game_state']['Row']

export type GameState = Omit<GameStateRow, 'inventory' | 'combat'> & {
  inventory: InventoryItem[]
  combat: CombatState | null
}
